export const perfumes = [
	{
		id: "481",
		slug: "481-kalimat",
		name: "Kalimat",
		gender: "Unisex",
		scentProfile: "Sweet, Amber, Woody",
		topNotes: ["Olibanum", "Basil"],
		heartNotes: ["Vanilla"],
		baseNotes: ["Agarwood (Oud)", "Amber"],
	},
	{
		id: "482",
		slug: "482-oud-mubakhar",
		name: "Oud Mubakhar",
		gender: "Unisex",
		scentProfile: "Smoky, Floral, Woody",
		topNotes: ["Floral Notes", "Woody Notes"],
		heartNotes: ["Rose", "Saffron"],
		baseNotes: ["Amber", "Oud"],
	},
	{
		id: "241",
		slug: "241-sauvage",
		name: "Sauvage",
		gender: "Male",
		scentProfile: "Fresh Spicy, Amber, Citrus",
		topNotes: ["Calabrian Bergamot", "Pepper"],
		heartNotes: ["Sichuan Pepper", "Lavender", "Geranium", "Vetiver", "Patchouli"],
		baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
	},
	{
		id: "121",
		slug: "121-ana-abiyedh",
		name: "Ana Abiadh",
		gender: "Unisex",
		scentProfile: "Sweet, Fruity, Musky",
		topNotes: ["Orange", "Bergamot"],
		heartNotes: ["Pear", "Vanilla"],
		baseNotes: ["Musk", "Dry Amber"],
	},
	{
		id: "242",
		slug: "242-one-million",
		name: "One Million",
		gender: "Male",
		scentProfile: "Warm Spicy, Cinnamon, Leather",
		topNotes: ["Blood Mandarin", "Grapefruit", "Mint"],
		heartNotes: ["Cinnamon", "Spicy Notes", "Rose"],
		baseNotes: ["Amber", "Leather", "Woody Notes", "Indian Patchouli"],
	},
	{
		id: "480",
		slug: "483-baccarat-rouge",
		name: "Baccarat Rouge",
		gender: "Unisex",
		scentProfile: "Amber Floral, Woody, Sweet",
		topNotes: ["Saffron", "Jasmine"],
		heartNotes: ["Amberwood", "Ambergris"],
		baseNotes: ["Fir Resin", "Cedar"],
	},
	{
		id: "124",
		slug: "124-paris-hilton",
		name: "Paris Hill",
		gender: "Female",
		scentProfile: "Floral Fruity, Fresh",
		topNotes: ["Melon", "Apple", "Peach"],
		heartNotes: ["Freesia", "Mimosa", "Jasmine", "Lily-of-the-Valley", "Tuberose"],
		baseNotes: ["Musk", "Ylang-Ylang", "Sandalwood", "Oakmoss"],
	},
	{
		id: "23",
		slug: "123-fantasy",
		name: "Fantasy",
		gender: "Female",
		scentProfile: "Sweet, Fruity, Gourmand",
		topNotes: ["Kiwi", "Red Litchi", "Quince"],
		heartNotes: ["White Chocolate", "Cupcake", "Orchid", "Jasmine"],
		baseNotes: ["Musk", "Woodsy Notes", "Orris Root"],
	},
	{
		id: "122",
		slug: "122-invictus",
		name: "Inviktus",
		gender: "Male",
		scentProfile: "Citrus, Marine, Aromatic",
		topNotes: ["Sea Notes", "Grapefruit", "Mandarin Orange"],
		heartNotes: ["Bay Leaf", "Jasmine"],
		baseNotes: ["Ambergris", "Guaiac Wood", "Oakmoss", "Patchouli"],
	},
	{
		id: "243",
		slug: "243-terre-d-hermes",
		name: "Terre Dermes",
		gender: "Male",
		scentProfile: "Woody Spicy, Earthy, Citrus",
		topNotes: ["Orange", "Grapefruit"],
		heartNotes: ["Pepper", "Pelargonium (Geranium)"],
		baseNotes: ["Vetiver", "Cedar", "Patchouli", "Benzoin"],
	},
];
